#ifndef EG_DATABASE_H
#define EG_DATABASE_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void eg_database_create(void);
void eg_database_destroy(void);

eg_scene_asset_id_t eg_database_load_default_scene_asset_id(void);
eg_swapchain_asset_id_t eg_database_load_default_swapchain_asset_id(void);
eg_renderer_asset_id_t eg_database_load_default_renderer_asset_id(void);

eg_vector_t *eg_database_load_all_swapchain_assets(void);
eg_swapchain_asset_t eg_database_load_swapchain_asset_by_id(eg_swapchain_asset_id_t swapchain_asset_id);

eg_vector_t *eg_database_load_all_renderer_assets(void);
eg_renderer_asset_t eg_database_load_renderer_asset_by_id(eg_renderer_asset_id_t renderer_asset_id);

uint64_t eg_database_load_vertex_input_binding_count_by_id(eg_pipeline_asset_id_t pipeline_asset_id);
uint64_t eg_database_load_descriptor_binding_count_by_id(eg_pipeline_asset_id_t pipeline_asset_id);

eg_vector_t *eg_database_load_all_pipeline_assets(void);
eg_vector_t *eg_database_load_all_pipeline_assets_by_type(eg_pipeline_type_t pipeline_type);
eg_pipeline_asset_t eg_database_load_pipeline_asset_by_id(eg_pipeline_asset_id_t pipeline_asset_id);
eg_pipeline_resource_t eg_database_load_pipeline_resource_by_id(eg_pipeline_asset_id_t pipeline_asset_id);
eg_vector_t *eg_database_load_all_pipeline_vertex_input_bindings_by_id(eg_pipeline_asset_id_t pipeline_asset_id);
eg_vector_t *eg_database_load_all_pipeline_descriptor_bindings_by_id(eg_pipeline_asset_id_t pipeline_asset_id);

eg_vector_t *eg_database_load_all_model_assets(void);
eg_model_resource_t eg_database_load_model_resource_by_id(eg_model_asset_id_t model_asset_id);
eg_vector_t *eg_database_load_all_model_meshes_by_id(eg_model_asset_id_t model_asset_id);

eg_vector_t *eg_database_load_all_mesh_primitives_by_id(eg_model_mesh_id_t model_mesh_id);
eg_vector_t *eg_database_load_all_mesh_attributes_by_id(eg_mesh_primitive_id_t mesh_primitive_id);

eg_attribute_buffer_t eg_database_load_attribute_buffer_by_id(eg_mesh_attribute_id_t mesh_attribute_id);

eg_vector_t *eg_database_load_all_scene_assets(void);
eg_scene_asset_t eg_database_load_scene_asset_by_id(eg_scene_asset_id_t scene_asset_id);

eg_graph_asset_t eg_database_load_graph_asset_by_id(eg_graph_asset_id_t graph_asset_id);

void eg_database_store_swapchain_asset(eg_swapchain_asset_t *swapchain_asset);

void eg_database_store_renderer_asset(eg_renderer_asset_t *renderer_asset);

void eg_database_store_pipeline_asset(eg_pipeline_asset_t *pipeline_asset);
void eg_database_store_pipeline_resource(eg_pipeline_resource_t *pipeline_resource);
void eg_database_store_pipeline_vertex_input_binding(eg_pipeline_vertex_input_binding_t *pipeline_vertex_input_binding);
void eg_database_store_pipeline_descriptor_binding(eg_pipeline_descriptor_binding_t *pipeline_descriptor_binding);

void eg_database_store_model_asset(eg_model_asset_t *model_asset);
void eg_database_store_model_resource(eg_model_resource_t *model_resource);
void eg_database_store_model_mesh(eg_model_mesh_t *model_mesh);

void eg_database_store_mesh_primitive(eg_mesh_primitive_t *mesh_primitive);
void eg_database_store_mesh_attribute(eg_mesh_attribute_t *mesh_attribute);

void eg_database_store_attribute_buffer(eg_attribute_buffer_t *attribute_buffer);

void eg_database_store_scene_asset(eg_scene_asset_t *scene_asset);

void eg_database_store_graph_asset(eg_graph_asset_t *graph_asset);

void eg_database_destroy_swapchain_asset(eg_swapchain_asset_t *swapchain_asset);
void eg_database_destroy_swapchain_assets(eg_vector_t *swapchain_assets);

void eg_database_destroy_renderer_asset(eg_renderer_asset_t *renderer_asset);
void eg_database_destroy_renderer_assets(eg_vector_t *renderer_assets);

void eg_database_destroy_pipeline_asset(eg_pipeline_asset_t *pipeline_asset);
void eg_database_destroy_pipeline_assets(eg_vector_t *pipeline_assets);
void eg_database_destroy_pipeline_resource(eg_pipeline_resource_t *pipeline_resource);
void eg_database_destroy_pipeline_vertex_input_bindings(eg_vector_t *vertex_input_bindings);
void eg_database_destroy_pipeline_descriptor_bindings(eg_vector_t *descriptor_bindings);

void eg_database_destroy_model_assets(eg_vector_t *model_assets);
void eg_database_destroy_model_resource(eg_model_resource_t *model_resource);
void eg_database_destroy_model_meshs(eg_vector_t *model_meshes);

void eg_database_destroy_mesh_primitives(eg_vector_t *mesh_primitives);
void eg_database_destroy_mesh_attributes(eg_vector_t *mesh_attributes);

void eg_database_destroy_attribute_buffer(eg_attribute_buffer_t *attribute_buffer);

void eg_database_destroy_scene_asset(eg_scene_asset_t *scene_asset);
void eg_database_destroy_scene_assets(eg_vector_t *scene_assets);

void eg_database_destroy_graph_assets(eg_vector_t *graph_assets);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // EG_DATABASE_H
