/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Context */

#ifndef _Included_Context
#define _Included_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Context
 * Method:    createContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Context_createContext
  (JNIEnv *, jobject);

/*
 * Class:     Context
 * Method:    updateContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Context_updateContext
  (JNIEnv *, jobject);

/*
 * Class:     Context
 * Method:    destroyContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Context_destroyContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
