CREATE TABLE IF NOT EXISTS MODEL_ASSETS (
	ID         INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME       TEXT NOT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODEL_RESOURCES (
	ID              INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_ASSET_ID  INTEGER NOT NULL,
	MODEL_FILE_PATH TEXT,
	MODEL_BYTES     BLOB,
	CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (MODEL_ASSET_ID) REFERENCES MODEL_ASSETS(ID)
	UNIQUE (MODEL_ASSET_ID)
);

CREATE TABLE IF NOT EXISTS MODEL_MESHES (
	ID             INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_ASSET_ID INTEGER NOT NULL,
	CREATED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (MODEL_ASSET_ID) REFERENCES MODEL_ASSETS(ID)
	UNIQUE (MODEL_ASSET_ID)
);

CREATE TABLE IF NOT EXISTS MODEL_PRIMITIVES (
	ID            INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_MESH_ID INTEGER NOT NULL,
	CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (MODEL_MESH_ID) REFERENCES MODEL_MESHES(ID)
);

CREATE TABLE IF NOT EXISTS MODEL_ATTRIBUTES (
	ID                 INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_PRIMITIVE_ID INTEGER NOT NULL,
	NAME               TEXT NOT NULL,
	TYPE               INTEGER NOT NULL,
	VALUE_BYTES        BLOB NOT NULL,
	CREATED_AT         DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (MODEL_PRIMITIVE_ID) REFERENCES MODEL_ATTRIBUTES(ID)
);