CREATE TABLE IF NOT EXISTS MODEL (
	ID         INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME       TEXT NOT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	UNIQUE     (NAME)
);

CREATE TABLE IF NOT EXISTS MODEL_RESOURCES (
	ID              INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_ID        INTEGER NOT NULL,
	MODEL_FILE_PATH TEXT,
	CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY     (MODEL_ID) REFERENCES MODEL(ID)
	UNIQUE          (MODEL_ID)
);

CREATE TABLE IF NOT EXISTS MODEL_MESHES (
	ID          INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_ID    INTEGER NOT NULL,
	NAME        TEXT NOT NULL,
	CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (MODEL_ID) REFERENCES MODEL(ID)
	UNIQUE      (MODEL_ID)
);

CREATE TABLE IF NOT EXISTS MESH_PRIMITIVES (
	ID            INTEGER PRIMARY KEY AUTOINCREMENT,
	MODEL_MESH_ID INTEGER NOT NULL,
	NAME          TEXT NOT NULL,
	CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY   (MODEL_MESH_ID) REFERENCES MODEL_MESHES(ID)
);

CREATE TABLE IF NOT EXISTS MESH_ATTRIBUTES (
	ID                INTEGER PRIMARY KEY AUTOINCREMENT,
	MESH_PRIMITIVE_ID INTEGER NOT NULL,
	NAME              TEXT NOT NULL,
	TYPE              INTEGER NOT NULL,
	COUNT             INTEGER NOT NULL,
	CREATED_AT        DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY       (MESH_PRIMITIVE_ID) REFERENCES MESH_PRIMITIVES(ID)
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE_BUFFER (
	ID                INTEGER PRIMARY KEY AUTOINCREMENT,
	MESH_ATTRIBUTE_ID INTEGER NOT NULL,
	DATA              BLOB NOT NULL,
	CREATED_AT        DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY       (MESH_ATTRIBUTE_ID) REFERENCES MESH_ATTRIBUTES(ID)
)