CREATE TABLE IF NOT EXISTS PIPELINE_ASSETS (
	ID          INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME        TEXT NOT NULL,
	TYPE        INTEGER NOT NULL,
	LINK_INDEX  INTEGER NOT NULL,
	AUTO_CREATE INTEGER NOT NULL,
	CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PIPELINE_RESOURCES (
	ID                        INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID               INTEGER NOT NULL,
	VERTEX_SHADER_FILE_PATH   TEXT,
	FRAGMENT_SHADER_FILE_PATH TEXT,
	COMPUTE_SHADER_FILE_PATH  TEXT,
	VERTEX_SHADER             BLOB,
	FRAGMENT_SHADER           BLOB,
	COMPUTE_SHADER            BLOB,
	CREATED_AT                DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_ASSETS(ID)
	UNIQUE (PIPELINE_ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE_VERTEX_INPUT_BINDINGS (
	ID           INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID  INTEGER NOT NULL,
	BINDING_NAME TEXT NOT NULL,
	BINDING      INTEGER NOT NULL,
	LOCATION     INTEGER NOT NULL,
	STRIDE       INTEGER NOT NULL,
	FORMAT       INTEGER NOT NULL,
	OFFSET       INTEGER NOT NULL,
	INPUT_RATE   INTEGER NOT NULL,
	CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_ASSETS(ID),
	UNIQUE (PIPELINE_ID, LOCATION)
);

CREATE TABLE IF NOT EXISTS PIPELINE_DESCRIPTOR_BINDINGS (
	ID               INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID      INTEGER NOT NULL,
	BINDING_NAME     TEXT NOT NULL,
	BINDING          INTEGER NOT NULL,
	DESCRIPTOR_TYPE  INTEGER NOT NULL,
	DESCRIPTOR_COUNT INTEGER NOT NULL,
	STAGE_FLAGS      INTEGER NOT NULL,
	AUTO_BUFFER      INTEGER NOT NULL,
	CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_ASSETS(ID),
	UNIQUE (PIPELINE_ID, BINDING)
);