CREATE TABLE IF NOT EXISTS PIPELINE_CONFIGS (
	ID          INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME        TEXT NOT NULL,
	TYPE        INTEGER NOT NULL,
	AUTO_CREATE INTEGER NOT NULL,
	CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PIPELINE_RESOURCES (
	ID              INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID     INTEGER NOT NULL,
	VERTEX_SHADER   BLOB,
	FRAGMENT_SHADER BLOB,
	COMPUTE_SHADER  BLOB,
	CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_CONFIGS(ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE_VERTEX_INPUT_BINDING_DESCRIPTIONS (
	ID           INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID  INTEGER NOT NULL,
	BINDING_NAME TEXT NOT NULL,
	BINDING      INTEGER NOT NULL,
	STRIDE       INTEGER NOT NULL,
	INPUT_RATE   INTEGER NOT NULL,
	CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_CONFIGS(ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE_VERTEX_INPUT_ATTRIBUTE_DESCRIPTIONS (
	ID             INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID    INTEGER NOT NULL,
	ATTRIBUTE_NAME TEXT NOT NULL,
	LOCATION       INTEGER NOT NULL,
	BINDING        INTEGER NOT NULL,
	FORMAT         INTEGER NOT NULL,
	OFFSET         INTEGER NOT NULL,
	CREATED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_CONFIGS(ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE_DESCRIPTOR_POOL_SIZES (
	ID          INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID INTEGER NOT NULL,
	TYPE        INTEGER NOT NULL,
	COUNT       INTEGER NOT NULL,
	CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_CONFIGS(ID)
	UNIQUE (TYPE)
);

CREATE TABLE IF NOT EXISTS PIPELINE_DESCRIPTOR_SET_LAYOUT_BINDINGS (
	ID               INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID      INTEGER NOT NULL,
	BINDING_NAME     TEXT NOT NULL,
	BINDING          INTEGER NOT NULL,
	DESCRIPTOR_TYPE  INTEGER NOT NULL,
	DESCRIPTOR_COUNT INTEGER NOT NULL,
	STAGE_FLAGS      INTEGER NOT NULL,
	AUTO_BUFFER      INTEGER NOT NULL,
	CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_CONFIGS(ID)
	UNIQUE (BINDING)
);