CREATE TABLE IF NOT EXISTS RENDERER_ASSETS (
	ID               INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME             TEXT NOT NULL,
	FRAMES_IN_FLIGHT INTEGER NOT NULL,
	CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO RENDERER_ASSETS (NAME, FRAMES_IN_FLIGHT) VALUES
	('default', 1);