CREATE TABLE IF NOT EXISTS RENDERER (
	ID               INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME             TEXT NOT NULL,
	FRAMES_IN_FLIGHT INTEGER NOT NULL,
	IS_DEFAULT       INTEGER NOT NULL,
	CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO RENDERER (NAME, FRAMES_IN_FLIGHT, IS_DEFAULT) VALUES
	('default', 1, 1);