CREATE TABLE IF NOT EXISTS RENDERER_MAPPINGS (
	ID            INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID   INTEGER NOT NULL,
	LOGICAL_INDEX INTEGER NOT NULL,
	CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINE_CONFIGS(ID)
);