CREATE TABLE IF NOT EXISTS SCENE (
	ID         INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME       TEXT NOT NULL,
	IS_DEFAULT INTEGER NOT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SCENE (NAME, IS_DEFAULT) VALUES
	('test_level_0', 1),
	('test_level_1', 0),
	('test_level_2', 0);