CREATE TABLE IF NOT EXISTS SWAPCHAIN_ASSETS (
	ID           INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME         TEXT NOT NULL,
	IMAGE_COUNT  INTEGER NOT NULL,
	DEPTH_FORMAT INTEGER NOT NULL,
	CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SWAPCHAIN_ASSETS (NAME, IMAGE_COUNT, DEPTH_FORMAT) VALUES
	('default', 1, 126);