CREATE TABLE IF NOT EXISTS SWAPCHAIN (
	ID           INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME         TEXT NOT NULL,
	IMAGE_COUNT  INTEGER NOT NULL,
	DEPTH_FORMAT INTEGER NOT NULL,
	IS_DEFAULT   INTEGER NOT NULL,
	CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SWAPCHAIN (NAME, IMAGE_COUNT, DEPTH_FORMAT, IS_DEFAULT) VALUES
	('default', 1, 126, 1);