CREATE TABLE IF NOT EXISTS PIPELINES (
	ID         INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME       TEXT NOT NULL,
	TYPE       INTEGER NOT NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GRAPHIC_PIPELINE_SETTINGS (
	ID              INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID     INTEGER NOT NULL,
	VERTEX_SHADER   BLOB NOT NULL,
	FRAGMENT_SHADER BLOB NOT NULL,
	CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINES(ID)
);

CREATE TABLE IF NOT EXISTS COMPUTE_PIPELINE_SETTINGS (
	ID             INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID    INTEGER NOT NULL,
	COMPUTE_SHADER BLOB NOT NULL,
	CREATED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINES(ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE_BINDING_SETTINGS (
	ID             INTEGER PRIMARY KEY AUTOINCREMENT,
	PIPELINE_ID    INTEGER NOT NULL,
	BINDING_NAME   TEXT NOT NULL,
	NO_AUTO_BUFFER BOOLEAN NOT NULL,
	CREATED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PIPELINE_ID) REFERENCES PIPELINES(ID)
);