#ifndef RENDERER_CONFIG_H
#define RENDERER_CONFIG_H

#include <stdint.h>

#define RENDERER_CHUNK_COUNT_X (3LL)
#define RENDERER_CHUNK_COUNT_Y (1LL)
#define RENDERER_CHUNK_COUNT_Z (3LL)

#define RENDERER_CHUNK_SIZE (256LL)

#define RENDERER_CLUSTER_VERTEX_COUNT (8LL)
#define RENDERER_CLUSTER_INDEX_COUNT (36LL)

#define RENDERER_DEBUG_LINE_VERTEX_COUNT (1048576LL)
#define RENDERER_DEBUG_LINE_INDEX_COUNT (1048576LL)

#endif // RENDERER_CONFIG_H
