#ifndef CORE_CONFIG_H
#define CORE_CONFIG_H

#include <stdint.h>

#define CORE_STRING_BUFFER_CAPACITY (16ULL)
#define CORE_STRING_BUFFER_ALIGNMENT (16ULL)

#define CORE_VECTOR_BUFFER_CAPACITY (16ULL)
#define CORE_VECTOR_BUFFER_ALIGNMENT (16ULL)

#endif // CORE_CONFIG_H
